apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pumpkin-spice-hpa
  labels:
    app: pumpkin-spice
    version: 0.0.1
    backstage.io/kubernetes-id: pumpkin-spice
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pumpkin-spice
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75